# Generated by Django 4.1.5 on 2023-05-21 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adresse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(blank=True, max_length=20, unique=True)),
                ('email', models.CharField(max_length=250, unique=True)),
                ('quartier', models.CharField(max_length=200)),
                ('ville', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Etablissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=150)),
                ('nom', models.CharField(max_length=150)),
                ('arrete', models.CharField(max_length=150)),
                ('date', models.CharField(max_length=150)),
                ('logo', models.ImageField(blank=True, upload_to='static/logo')),
            ],
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('coefficient', models.FloatField(max_length=15)),
                ('note', models.FloatField(max_length=15)),
                ('appreciation', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('prenom', models.CharField(max_length=100)),
                ('naissance', models.DateTimeField(verbose_name='date de naissance')),
                ('lieu', models.CharField(max_length=100)),
                ('genre', models.CharField(choices=[('Masculin', 'Masculin'), ('Feminin', 'Feminin')], max_length=32)),
                ('nationnalite', models.CharField(max_length=50)),
                ('photo', models.ImageField(blank=True, upload_to='static/photo')),
            ],
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('personne_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='education.personne')),
                ('matricule', models.CharField(max_length=32)),
                ('grade', models.CharField(max_length=100)),
                ('poste', models.CharField(max_length=100)),
                ('type_poste', models.CharField(max_length=100)),
                ('adresse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.adresse')),
                ('matiere', models.ManyToManyField(to='education.matiere')),
            ],
            bases=('education.personne',),
        ),
        migrations.CreateModel(
            name='Eleve',
            fields=[
                ('personne_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='education.personne')),
                ('matricule', models.CharField(max_length=32, unique=True)),
                ('status', models.CharField(choices=[('Ancien', 'Ancien'), ('Nouveau', 'Nouveau')], max_length=32)),
                ('niveau', models.CharField(choices=[('6', 'Licence 1'), ('5', 'Licence 2'), ('4', 'Licence 3'), ('3', 'Licence 2'), ('Second', 'Licence 3'), ('premiere', 'Licence 1'), ('terminal', 'Licence 2')], max_length=32)),
                ('serie', models.CharField(choices=[('Litteraire', 'Ancien'), ('Scientifique', 'Nouveau'), ('Technique commerçiale', 'Ancien'), ('Technique Industrielle', 'Nouveau')], max_length=32)),
                ('Matiere', models.ManyToManyField(to='education.matiere')),
                ('adresse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.adresse', unique=True)),
            ],
            bases=('education.personne',),
        ),
    ]
