# Generated by Django 2.2.12 on 2023-06-10 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personnel',
            name='type_poste',
        ),
        migrations.AlterField(
            model_name='adresse',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='niveau',
            field=models.CharField(choices=[('6 eme', '6 eme'), ('5 eme', '5 eme'), ('4 eme', '4 eme'), ('3 eme', '3 eme'), ('Second', 'Second'), ('premiere', 'premiere'), ('terminal', 'terminale')], max_length=32),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='serie',
            field=models.CharField(choices=[('Litteraire', 'Litterature'), ('Scientifique', 'Scince'), ('Technique commerçial', 'Technique Commerçial'), ('Technique Industrielle', 'Technique Industrielle')], max_length=32),
        ),
        migrations.AlterField(
            model_name='etablissement',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='matiere',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='personne',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
