# Generated by Django 2.2.12 on 2023-06-27 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_auto_20230610_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleve',
            name='adresse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.Adresse'),
        ),
    ]
